const mongoose = require("mongoose");
const Product = require("./models/Product");
const User = require("./models/User");
require("dotenv").config();

const products = [
  { name: "Velvet Matte Lipstick", brand: "Sephora", price: 15, category: "lipstick", image: "https://www.temptalia.com/wp-content/uploads/2023/07/sephora_matte-velvet-lipstick_004_product.jpg", stock: 50, description: "Achieve a flawless, velvety matte finish that lasts all day with our Velvet Matte Lipstick. This luxurious formula glides on smoothly and sets to a comfortable, non-drying matte finish. Infused with nourishing oils and vitamin E, it keeps your lips soft while delivering intense color payoff. Perfect for everyday wear or special occasions.", rating: 4.8, reviewCount: 234, isFeatured: true, colors: [
    { name: "Bright Pink", hex: "#f84672" },
    { name: "Soft Rose Pink", hex: "#aa3a65" },
    { name: "Deep Burgundy", hex: "#5f2a30" },
    { name: "Muted Berry", hex: "#9e2842" },
    { name: "Warm Brick Red", hex: "#702329" }] 
  },
  { name: "Pro Glow Foundation", brand: "Charlotte Tilbury", price: 58, category: "foundation", image: "https://cdn-cjhgk.nitrocdn.com/CXxGixRVyChwAxySbAyltuCiQXRKaWDN/assets/images/optimized/rev-9dad235/www.newbeauty.com/wp-content/uploads/2024/06/charlotte-tilbury-foundation-stick-2.jpg", stock: 35, description: "This revolutionary foundation stick combines the benefits of a concealer, foundation, and contour in one easy-to-use product. The creamy, blendable formula provides medium to full coverage while delivering a gorgeous, natural-looking glow. Enriched with hyaluronic acid and radiance-boosting pigments, it hydrates and illuminates your skin for a flawless finish that lasts all day.", rating: 4.7, reviewCount: 189, colors: [
    { name: "Fair", hex: "#ecc1a0" },
    { name: "Medium", hex: "#fcb377" },
    { name: "Tan", hex: "#c8794a" },
    { name: "Deep", hex: "#512e28" }] 
  },
  { name: "Hydrating Face Cream", brand: "La Mer", price: 85, category: "skincare", image: "https://www.sephora.com/productimages/product/p416341-av-19-zoom.jpg?imwidth=3000", stock: 28, description: "Experience the legendary hydration of La Mer with this iconic Crème de la Mer. This rich, luxurious moisturizer transforms skin, delivering deep hydration and visible transformation. Infused with the proprietary Miracle Broth™, this cult-favorite cream helps calm and nourish skin while reducing the appearance of fine lines and wrinkles. Perfect for those seeking ultimate hydration and a radiant, youthful complexion.", rating: 4.9, reviewCount: 312, sizes: ["15ml", "30ml", "60ml"] },
  { name: "Naked Palette", brand: "Urban Decay", price: 54, category: "eyeshadow", image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi0kwdJYKMKNF_TLmsiGtIL8djgY0_M9UjM60Ds9RJSRZ2P3vESaw71lMuInv1Vd44ROW6fTLBAEEjxPalhcJPA0Jb1qfgL1CPmrRafaBVERRfczwXzdjYarmNtbz5KkAZ9JHWg4BPYknpQ/s1600/IMG_09512.jpg", stock: 42, description: "The original, iconic Naked Palette that started it all. This versatile eyeshadow palette features 12 universally-flattering shades in matte, satin, and shimmer finishes. From soft neutrals to smoky darks, create endless eye looks from natural daytime to dramatic evening makeup. The buttery-smooth formula blends effortlessly and lasts up to 12 hours without creasing or fading.", rating: 4.6, reviewCount: 156, isTrending: true, shadeVariants: [
    { name: "Naked", shades: ["#dbbfbe", "#c19da1", "#c69a8a", "#a27268", "#ac7d6d", "#dba583", "#9f6248", "#69493e", "#b98c87", "#785358", "#32323e", "#46506b"] },
    { name: "Naked 2", shades: ["#eddfd4", "#e8be9b", "#ebd7d6", "#c88e7d", "#cba8ae", "#865a51", "#ac8a88", "#8f807e", "#d8caca", "#d2b2b2", "#6f5159", "#1c1b23"] },
    { name: "Naked 3", shades: ["#e4d3d9", "#d7a9b7", "#cb939d", "#d6a8b5", "#c18496", "#d6a29e", "#b48393", "#b48393", "#a47887", "#b18992", "#795a6a", "#4d3340"] },
    { name: "Smoky", shades: ["#debbb9", "#deaa92", "#976254", "#9d8f9b", "#96a1b8", "#586084", "#444a5f", "#5a4763", "#998497", "#906150", "#dfc7c7", "#e9e0e1"] }
  ]},
  { name: "Lash Sensational - Sky High", brand: "Maybelline", price: 12, category: "mascara", image: "https://images.squarespace-cdn.com/content/v1/5d14e8bfa505890001205e37/1752857301108-WZDCYVZAH2RDS3WQWGVS/avis-maybelline-mascara-sky-high-test-revue-swatches-green-altitude-burgundy-haze-space-diamond-plum-twilight-pauuulette+%287%29.jpg?format=1500w", stock: 100, description: "Get ready for sky-high lashes with this viral mascara! The unique Swan-neck wand bends to grab every lash from root to tip, even the hardest-to-reach corner lashes. The ultra-black formula coats each lash for dramatic volume and length that lasts all day. Smudge-proof and humidity-resistant, this mascara delivers instant lash extension without clumps or flaking.", rating: 4.5, reviewCount: 445, colors: [
    { name: "Green Altitude", hex: "#3b4b44" },
    { name: "Burgundy Haze", hex: "#611737" },
    { name: "Space Diamond", hex: "#ceced2" },
    { name: "Plum Twilight", hex: "#3f2b56" }] 
  },
  { name: "Orgasm Blush", brand: "NARS", price: 42, category: "blush", image: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lg2eju5a2nhm6c", stock: 38, description: "The iconic Orgasm Blush that started a revolution. This award-winning, universally-flattering shade features a peachy-pink with golden shimmer that creates a natural, sun-kissed glow. The silky powder blends seamlessly for a buildable, sheer to medium coverage that mimics a healthy flush. Infused with light-reflecting microspheres, it adds a subtle luminosity that looks like you're glowing from within.", rating: 4.8, reviewCount: 267},
  { name: "Diamond Bomb Highlighter", brand: "Fenty Beauty", price: 36, category: "highlighter", image: "https://www.edgars.co.za/cdn/shop/files/DiamondBomb4.jpg?v=1762327007&width=1800", stock: 45, description: "All that glitter? Yes, gold! Diamond Bomb is a prismatic, multi-dimensional highlighter that delivers an explosive, all-over glow. This weightless formula feels like crushed diamonds on your skin, leaving an intense, glass-like finish. The light-reflecting particles catch every angle of light for a blinding highlight that lasts up to 10 hours. Apply to cheekbones, brow bones, cupid's bow, or anywhere you want serious shimmer.", rating: 4.7, reviewCount: 198, colors: [
    { name: "Pink Ice", hex: "#e2dedb" },
    { name: "Lavender Luv'r", hex: "#dfa0c5" },
    { name: "Trophy Wife", hex: "#cca94b" }] 
  },
  { name: "Cheek Pop Blush Stick", brand: "Shiseido", price: 32, category: "blush", image: "https://www.faceandbody.sg/cdn/shop/files/sg-11134207-7rasp-macq9mys708j54.jpg?v=1748522752&width=416", stock: 40, description: "Achieve a natural, flushed look with Shiseido's Cheek Pop. This soft powder blush delivers a translucent, natural flush with buildable color payoff. The finely milled formula applies smoothly without patchiness and blends seamlessly into the skin for a fresh, healthy-looking glow. The compact design makes it perfect for on-the-go touch-ups, while the signature floral fragrance adds a delightful sensory experience.", rating: 4.6, reviewCount: 156, colors: [
    { name: "Romantic", hex: "#9b3833" },
    { name: "First Date", hex: "#cb646b" },
    { name: "Puppy Love", hex: "#e07b7d" },
    { name: "You & I", hex: "#b96254" },
    { name: "Valentine's", hex: "#8f5161" },
    { name: "My Universe", hex: "#a35881" }]
  },
  { name: "Glow Macaron Highlighter", brand: "Becca", price: 38, category: "highlighter", image: "https://i.pinimg.com/736x/62/8f/da/628fda5d8c02b06c743ece9d4eb32563.jpg", stock: 35, description: "Inspired by French macarons, this adorable compact highlighter delivers a soft, luminous glow with a delicate, baked texture. The silky formula melts into skin for a natural, lit-from-within radiance that's never glittery or chunky. Perfect for creating that dewy, fresh-faced look, each shade is designed to complement different skin tones and enhance your natural beauty.", rating: 4.8, reviewCount: 234, colors: [
    { name: "Opal", hex: "#c7aba0" },
    { name: "Vanilla Quartz", hex: "#eae3dd" },
    { name: "Rose Quartz", hex: "#eec5cb" },
    { name: "Prismatic Amethyst", hex: "#dfd7e6" }
  ]},
  { name: "Blush In Bloom Palette", brand: "Tarte", price: 28, category: "blush", image: "https://i.makeup.fr/2/27/27sowjlu6smx.jpg", stock: 45, description: "This ready-to-wear blush palette features three complementary shades that can be used individually or swirled together for a custom flush. The Amazonian clay-infused formula improves skin's texture over time while providing smooth, blendable color that lasts up to 12 hours. The warm-toned palette suits a variety of skin tones and creates looks from subtle to bold.", rating: 4.5, reviewCount: 189},
  { name: "Lite Stix", brand: "ColourPop", price: 16, category: "highlighter", image: "https://www.temptalia.com/wp-content/uploads/2019/05/colour-pop_lite-stix_001_product.jpg", stock: 50, description: "These innovative highlighter sticks deliver a blinding, liquid-glow finish in a convenient solid form. The creamy, non-drying formula glides on smoothly and blends seamlessly into skin for a natural, dewy radiance. Ultra-portable and mess-free, these stick highlighters are perfect for touching up on the go. The versatile shades work beautifully on all skin tones for a customizable glow.", rating: 4.4, reviewCount: 312, colors: [
    { name: "Urth", hex: "#e8b599" },
    { name: "Star Brite", hex: "#eddfd6" },
    { name: "Flying High", hex: "#e59c9b" },
    { name: "Bullz Eye", hex: "#e6a877" },
    { name: "Acting Up", hex: "#dc7a59" }
  ]},
  { name: "Vitamin C Serum", brand: "The Ordinary", price: 15, category: "skincare", image: "https://www.cultbeauty.com/images?url=https://static.thcdn.com/productimg/original/12243648-9575317605891885.jpg&format=webp&auto=avif&width=1200&height=1200&fit=cover", stock: 80, description: "This powerful antioxidant serum features 100% pure L-Ascorbic Acid powder to help reduce the appearance of dark spots, brighten skin tone, and protect against environmental damage. The powder format allows you to customize the concentration by mixing with your favorite serum or moisturizer. Regular use reveals more radiant, even-toned skin over time.", rating: 4.6, reviewCount: 523, sizes: ["30ml", "60ml"] },
  { name: "Hydrating Lip Oil", brand: "Dior", price: 38, category: "lipstick", image: "https://imgmediagumlet.lbb.in/media/2025/09/68c13576d755eb1ec0502d1e_1757492598545.jpg", stock: 32, description: "Experience the ultimate lip treatment with Dior's iconic lip oil. This non-sticky, glossy formula delivers intense hydration and a mirror-like shine while letting your natural lip color show through. Infused with nourishing cherry oil and plumping hyaluronic acid, it cares for lips while providing a subtle tint and delicious scent. Perfect for achieving that coveted juicy lip look.", rating: 4.9, reviewCount: 145, colors: [
    { name: "Pink", hex: "#f19c9f" },
    { name: "Coral", hex: "#e94e18" },
    { name: "Rasberry", hex: "#ea3d71" },
    { name: "Berry", hex: "#7e065d" }
  ]},
  { name: "Ultra Fine Setting Spray", brand: "Make Up For Ever", price: 32, category: "makeup", image: "https://www.adorebeauty.co.nz/pim_media/000/433/166/MAKE_UP_FOR_EVER_Mist___Fix_Matte_both_sizes.png", stock: 55, description: "Lock your makeup in place with this cult-favorite setting spray. The ultra-fine mist delivers a flawless, refreshed look while extending makeup wear for up to 16 hours. The alcohol-free formula sets makeup without changing its appearance, ensuring your look stays fresh from morning to night. Simply spray over finished makeup for a seamless, professional finish.", rating: 4.5, reviewCount: 234, sizes: ["30ml", "100ml"] },
  { name: "Hyaluronic Acid Serum", brand: "CeraVe", price: 22, category: "skincare", image: "https://www.cerave.co.uk/-/media/project/loreal/brand-sites/cerave/emea/uk/products/ha-serum/ha-serum-front-lg.jpg?rev=-1?w=500&hash=0735B4BC1C080328DC5EE2473E9B8EF7", stock: 75, description: "This lightweight, oil-free serum delivers intense hydration with multiple forms of hyaluronic acid. The dermatologist-developed formula helps retain skin's natural moisture while restoring the skin's protective barrier with essential ceramides. Gentle enough for sensitive skin and non-comedogenic, it leaves skin feeling smooth, hydrated, and refreshed without greasiness.", rating: 4.7, reviewCount: 412 },
  { name: "Glow Recipe Serum", brand: "Glow Recipe", price: 45, category: "skincare", image: "https://www.cultbeauty.com/images?url=https://static.thcdn.com/productimg/original/15448252-7385174523375984.jpg&format=webp&auto=avif&width=700&height=700&fit=cover&dpr=2", stock: 40, description: "This vitamin C serum is infused with watermelon extract and AHA-rich fermented compounds for a brightening boost. The innovative formula visibly reduces dark spots and hyperpigmentation while gently exfoliating for smoother, more radiant skin. The antioxidant-rich blend protects against environmental stressors, leaving your complexion glowing, even, and luminous with regular use.", rating: 4.8, reviewCount: 289, colors: [
    { name: "Cloudberry Bright", hex: "#fda000" },
    { name: "Plum Plump", hex: "#f35f7b" },
    { name: "Strawberry Smooth", hex: "#cc1819" },
    { name: "Watermelon Glow", hex: "#fe8e9f" }
  ]},
  { name: "Better Than Sex Mascara", brand: "Too Faced", price: 26, category: "mascara", image: "https://secretsglow.ma/wp-content/uploads/2024/12/IMG_3919.png", stock: 60, description: "This award-winning mascara lives up to its name with dramatic, voluminous lashes. The signature hourglass-shaped wand separates and coats every lash for extreme volume and length. The collagen-infused formula lifts and curls while the thick bristles deposit maximum product without clumping. Waterproof and smudge-proof, it stays put all day for consistently dramatic lashes.", rating: 4.6, reviewCount: 378 },
  { name: "Contour Kit - Matte", brand: "Anastasia Beverly Hills", price: 48, category: "makeup", image: "https://m.media-amazon.com/images/I/51fcS9NXi2L._AC_UF1000,1000_QL80_.jpg", stock: 28, description: "Sculpt and define your features like a pro with this comprehensive contour kit. Featuring six matte shades ranging from light to dark, this versatile palette allows you to create depth and dimension for a chiseled, camera-ready look. The finely milled, blendable formulas melt seamlessly into skin for a natural, sun-cast shadow effect. Perfect for carving cheekbones, defining the nose, and shaping the jawline.", rating: 4.7, reviewCount: 198},
  { name: "Cloud Paint Lip Gloss", brand: "Glossier", price: 16, category: "lipstick", image: "https://sidewalkhustle.com/wp-content/uploads/2017/11/glossier-cloud-paint-quad-1.jpg", stock: 90, description: "Achieve that just-pinched rosy flush with these weightless, blendable cheek stains. The gel-cream formula melts into skin for a natural, second-skin finish that looks like you just came in from the cold. Buildable color lets you go from subtle to bold, while the dewy finish gives skin a healthy, lit-from-within glow. Long-lasting and seamless, it's the ultimate effortless flush.", rating: 4.5, reviewCount: 312, colors: [
    { name: "Bean", hex: "#bc7e6e" },
    { name: "Puff", hex: "#d26e82" },
    { name: "Haze", hex: "#bd5c4d" },
    { name: "Dusk", hex: "#870550" }
  ]},
  { name: "Silk Pillowcase", brand: "Slip", price: 35, category: "other", image: "https://media.self.com/photos/668ebbace307072919298676/4:3/w_4000,h_3000,c_limit/Best%20Silk%20Pillowcases%20062024%20Lede.jpg", stock: 50, description: "Transform your beauty sleep with our luxurious mulberry silk pillowcase. The smooth, frictionless surface helps reduce hair frizz and breakage while keeping your skin soft and crease-free. Made from 100% pure silk with a high momme weight for durability and ultimate comfort. Available in beautiful colors to complement any bedroom decor.", rating: 4.8, reviewCount: 167, colors: [
    { name: "Light Blue", hex: "#c9d7e0" },
    { name: "Light Pink", hex: "#dcc1be" },
    { name: "Light Green", hex: "#b6c2a5" }
  ]},
  { name: "Bijoux Brilliance", brand: "Pat McGrath", price: 64, category: "eyeshadow", image: "https://static.thcdn.com/productimg/original/14940282-6135094180608238.jpg", stock: 25, description: "Created by legendary makeup artist Pat McGrath, this high-end eyeshadow palette features jewel-toned pigments that capture and reflect light for an otherworldly glow. The velvety, ultra-pigmented formulas glide on like butter and blend seamlessly for a multi-dimensional finish. Each shade is crafted with innovative color technology to deliver intense color payoff that lasts up to 12 hours without creasing or fading.", rating: 4.9, reviewCount: 123, shadeVariants: [
    { name: "Jeweled Temptation", shades: ["#d7546d", "#742936", "#8b557e", "#c77150", "#e99f53", "#984d40", "#e6a794", "#752f2d", "#a45d44", "#e57968", "#e35549"] },
    { name: "Starstruck Splendour", shades: ["#fb8378", "#fcb8b4", "#bbc9ab", "#da8d77", "#fbb7b5", "#b95357", "#e0b397", "#ac6e7a", "#586a42", "#b4624c", "#bd7b56"] }
  ]},
  { name: "Double Wear Foundation", brand: "Estée Lauder", price: 52, category: "foundation", image: "https://www.esteelauder.com/media/export/cms/products/640x640/el_prod_141225_640x640_5.jpg", stock: 40, description: "Experience flawless, transfer-resistant coverage that lasts up to 24 hours with Double Wear Foundation. This lightweight, breathable formula stays fresh and natural-looking from morning to night, even in heat and humidity. The buildable coverage allows you to customize from medium to full coverage while the oil-free formula controls shine without drying skin. Available in 62 shades for a perfect match.", rating: 4.7, reviewCount: 234, colors: [
    { name: "Very Light", hex: "#deb388" },
    { name: "Warm Beige", hex: "#d6a67f" },
    { name: "Medium", hex: "#c2885a" },
    { name: "Tan", hex: "#986337" },
    { name: "Deep", hex: "#644032" }
  ]},
  { name: "Rose Gold Palette", brand: "Huda Beauty", price: 58, category: "eyeshadow", image: "https://5.imimg.com/data5/SELLER/Default/2023/12/372962494/YP/DF/FF/28051373/huda-beauty-rose-gold-palette.jpg", stock: 35, description: "Inspired by rose gold jewelry, this stunning palette features 9 universally-flattering shades ranging from soft champagne to deep bronze. The versatile mix of metallic, matte, and shimmer finishes allows you to create endless eye looks from subtle daytime radiance to glamorous evening drama. Each highly-pigmented shade is blendable and long-lasting for a flawless finish.", rating: 4.8, reviewCount: 189, isTrending: true },
  { name: "Retinol Night Cream", brand: "Paula's Choice", price: 68, category: "skincare", image: "https://hrd-live.cdn.scayle.cloud/images/23c903498219fed497765b2b92d5d032.jpg?quality=75", stock: 45, description: "Transform your skin overnight with this powerful retinol night cream. Formulated with 0.5% pure retinol, this intensive treatment reduces the appearance of fine lines, wrinkles, and uneven skin tone while you sleep. The rich, non-irritating formula is enhanced with antioxidants and peptides to boost collagen production and restore skin's youthful radiance. Wake up to smoother, firmer, more radiant-looking skin.", rating: 4.6, reviewCount: 267 },
  { name: "Waterproof Eyeliner - Black", brand: "Stila", price: 18, category: "mascara", image: "https://www.stilacosmetics.com/cdn/shop/files/BEST-OF-BEAUTY--ALLURE-2021.jpg?v=1705600717", stock: 70, description: "Achieve precise, smudge-proof eye looks with Stila's iconic waterproof eyeliner. The smooth, creamy formula glides on effortlessly for a flawless line while the waterproof, fade-proof formula stays put for up to 12 hours. The fine-tip applicator allows for both thick and thin lines, making it perfect for everything from natural everyday looks to dramatic smoky eyes.", rating: 4.7, reviewCount: 345 },
  { name: "Glow Bronzer ", brand: "Ucanbe", price: 34, category: "makeup", image: "https://m.media-amazon.com/images/I/71yLXpvrDSL._SL1500_.jpg", stock: 55, description: "Get that sun-kissed, healthy glow all year round with this ultra-blendable bronzer. The fine-milled formula builds naturally for a subtle warmth or layers for a more defined, sculpted look. Enriched with light-reflecting particles, it adds dimension and warmth without looking muddy or orange. The smooth texture blends seamlessly into skin for a natural, sun-warmed radiance.", rating: 4.5, reviewCount: 198, colors: [
    { name: "Light Bronzer", hex: "#d9b1a5" },
    { name: "Bronzer", hex: "#fbb989" },
    { name: "Sunkissed Bronzer", hex: "#da9f77" }
  ]},
  { name: "Glossy Lip Kits Collection", brand: "Kylie Cosmetics", price: 28, category: "lipstick", image: "https://kyliecosmetics.com/cdn/shop/files/v1_Glossy-Lip-Kit_PDP_wwli_2ea193ef-9647-43df-a474-a23c4f3456d5.jpg?crop=center&height=700&v=1750430713&width=756", stock: 65, description: "Complete your lip look with Kylie Cosmetics' signature glossy lip kits. Each kit includes a matching lip liner and gloss for perfectly coordinated lips. The long-wear liners define and shape your lips, while the high-shine glosses deliver mirror-like dimension with a non-sticky formula. Available in a variety of wearable shades from nudes to bold colors.", rating: 4.6, reviewCount: 156, colors: [
    { name: "Espresso", hex: "#692f25" },
    { name: "Dolce K", hex: "#a6584e" },
    { name: "Coconut 2.0", hex: "#c26257" },
    { name: "Comes Naturally", hex: "#ce6a62" },
    { name: "Kylie", hex: "#b85f63" },
    { name: "Candy Pink", hex: "#ec2f8d" }
  ]},
  { name: "Acne Control Kit", brand: "Mario Badescu", price: 32, category: "skincare", image: "https://www.mariobadescu.com/cdn/shop/files/shlcbueohwbwgl3gw3g4_eca81f08-744c-4db8-bb35-33e723a61121.jpg?v=1702450332&width=990", stock: 50, description: "Fight acne effectively with this comprehensive skincare kit from Mario Badescu. The kit includes a gentle cleansing spray, drying lotion for spot treatment, and a soothing moisturizer to help clear and prevent breakouts. Formulated with effective yet gentle ingredients like silver, zinc, and botanical extracts, this system works to reduce blemishes while maintaining skin's natural balance.", rating: 4.4, reviewCount: 289 },
  { name: "Volumizing Mascara - Noir Balm", brand: "L'Oréal", price: 24, category: "mascara", image: "https://target.scene7.com/is/image/Target/GUEST_d6dcb955-c4e2-4dbf-b9c7-8800b3cf0958?wid=1200&hei=1200&qlt=80", stock: 85, description: "Get dramatic volume with a nourishing treatment in one with this innovative mascara. The conditioning balm-enriched formula coats each lash for incredible volume while conditioning and softening. The unique brush separates and volumizes lashes from root to tip without clumping. Removes easily with warm water for hassle-free cleanup.", rating: 4.5, reviewCount: 456 },
  { name: "Setting Powder - Translucent", brand: "Charlotte Tilbury", price: 38, category: "makeup", image: "https://zwine.ma/cdn/shop/products/AFF-Finish_1.jpg?v=1673549401&width=500", stock: 40, description: "Achieve a flawless, airbrushed finish with this luxurious setting powder. The ultra-fine, translucent powder sets makeup for up to 12 hours while controlling shine and minimizing the appearance of pores. The light-reflecting formula leaves skin with a soft-focus, ethereal glow without adding weight or coverage. Perfect for all skin tones.", rating: 4.8, reviewCount: 178, colors: [
    { name: "Light", hex: "#f7e2c9" },
    { name: "Medium", hex: "#eec4a3" },
    { name: "Tan", hex: "#eaa36e" },
    { name: "Deep", hex: "#b36b42" }
  ]},
  { name: "Niacinamide Serum 20%", brand: "Paula's Choice", price: 25, category: "skincare", image: "https://www.paulaschoice.com.au/dw/image/v2/BBNX_PRD/on/demandware.static/-/Sites-pc-catalog/default/dwdc07a976/images/products/DTC-8030-5TAU-Key-Ingredients.png?sw=1000&sfrm=png", stock: 60, description: "Minimize pores, smooth skin texture, and fade dark spots with this potent 20% niacinamide serum. This multitasking formula also helps regulate oil production, strengthen the skin's barrier, and reduce redness. The lightweight, water-based serum absorbs quickly and works for all skin types. Pair with vitamin C for maximum brightening benefits.", rating: 4.7, reviewCount: 367 },
  { name: "Matte Lip Kit ", brand: "Kylie Cosmetics", price: 44, category: "lipstick", image: "https://akns-images.eonline.com/eol_images/Entire_Site/2022816/rs_1027x759-220916140329-1024-ecomm-Kylie-Cosmetics-Lip-Kits.ct.jpg?fit=around%7C1027:759&output-quality=90&crop=1027:759;center,top", stock: 38, description: "Get the signature Kylie matte lip with this versatile lip kit. Each kit includes a matching matte lipstick and lip liner for a flawless, long-wear lip look. The velvety matte formula applies smoothly and sets to a comfortable, non-drying finish that lasts for hours without feathering or bleeding. Available in a range of nude and bold shades.", rating: 4.6, reviewCount: 212, colors: [
    { name: "Soft Nude Pink", hex: "#e49e95" },
    { name: "Dusty Rose", hex: "#e2878c" },
    { name: "Classic Kylie Red", hex: "#ed2a36" },
    { name: "Peachy Nude", hex: "#d34d6a" },
    { name: "Caramel Brown Nude", hex: "#b97d62" }
  ]},
  { name: "Pro Brush Set", brand: "Morphe", price: 89, category: "other", image: "https://www.efsbeauty.com/cdn/shop/files/Morphe_RoseGold_TravelSet_PDP_1400x_2x_d6763267-7aab-441e-8199-8f603ac774c2.webp?v=1704911996&width=1946", stock: 30, description: "Elevate your makeup game with this professional-quality brush collection. The rose gold set includes everything you need for flawless face and eye makeup application. Each brush features ultra-soft, synthetic bristles that are cruelty-free and easy to clean. The ergonomic handles provide a comfortable grip for professional-level precision and blending. Comes in a chic travel case.", rating: 4.7, reviewCount: 145, isFeatured: true },
  { name: "Eye Cream - Anti Aging", brand: "Olay", price: 55, category: "skincare", image: "https://images.ctfassets.net/su0jtqat2bh5/5xKSiJKcInUx7NFMTAHuK8/412e5ae69b12e2cb4574c68a114b3e45/00075609010781_C1R1_M_NA__1_.png", stock: 45, description: "Target multiple signs of aging around your eyes with this powerful anti-aging eye cream. Formulated with peptides, vitamin B3, and黄瓜 extract, it reduces the appearance of fine lines, wrinkles, crow's feet, and puffiness. The lightweight, fast-absorbing formula hydrates without feeling heavy and can be used morning and night for visible results in as little as 4 weeks.", rating: 4.5, reviewCount: 234 },
  { name: "Brow Gel - Clear", brand: "Glossier", price: 16, category: "mascara", image: "https://glossier-prod.imgix.net/files/glossier-boybrow-brown-09.png?auto=compress,format&cs=srgb&w=1374", stock: 75, description: "Keep your brows in place all day with this clear brow gel. The quick-drying, non-sticky formula tames and sets brows while maintaining a natural look. The spoolie brush combs through hairs for a groomed, polished appearance. The subtle hold keeps brows shaped without feeling stiff or crunchy.", rating: 4.6, reviewCount: 289 },
  { name: "Priming Moisturizer", brand: "Smashbox", price: 42, category: "skincare", image: "https://b1998182.smushcdn.com/1998182/wp-content/uploads/2022/03/Smashbox-Photo-Finish-Primerizer-Primer-7.jpg?lossy=2&strip=1&webp=1", stock: 55, description: "Streamline your routine with this 2-in-1 primer and moisturizer that preps skin for flawless makeup application. The lightweight, oil-free formula hydrates while creating a smooth, even canvas for foundation. Infused with skincare ingredients like hyaluronic acid and antioxidants, it improves skin texture over time. Wear alone for a natural look or under makeup for all-day wear.", rating: 4.7, reviewCount: 198 },
  { name: "Lip Balm Set - Gift Box", brand: "Fresh", price: 22, category: "lipstick", image: "https://m.media-amazon.com/images/I/61iqt7rdNBL._AC_SL1000_.jpg", stock: 40, description: "Treat yourself or a loved one to this luxurious lip balm gift set from Fresh. Each balm is infused with natural ingredients like sugar, honey, and essential oils for intense hydration and a subtle sheen. The set includes a variety of signature scents including Brown Sugar, Honey, and Vanilla. The elegant packaging makes it perfect for gifting.", rating: 4.8, reviewCount: 167 },
  { name: "Concealer - Full Coverage", brand: "Tarte", price: 28, category: "makeup", image: "https://www.sephora.com/productimages/sku/s2252179-main-zoom.jpg?imwidth=1224", stock: 65, description: "Cover imperfections flawlessly with this full-coverage concealer. The creamy, blendable formula hides dark circles, blemishes, and redness with ease. The doe-foot applicator allows for precise application, while the buildable coverage lets you customize your finish. Infused with Amazonian clay, it actually helps balance skin and stay crease-free for 12 hours.", rating: 4.6, reviewCount: 312 },
  { name: "Face Oil - Rose", brand: "Drunk Elephant", price: 38, category: "skincare", image: "https://static.thcdn.com/productimg/original/13317064-1715177668240749.jpg", stock: 35, description: "Achieve a radiant, dewy complexion with this lightweight facial oil. Formulated with a blend of nourishing seed and botanical oils, it sinks quickly into skin without leaving a greasy residue. The rose-centric blend includes Rosa Canina (rosehip) seed oil, which is rich in skin-loving fatty acids and vitamins. Perfect for adding luminous glow to dry or dull skin.", rating: 4.7, reviewCount: 145 },
  { name: "Dramatic Lashes Mascara", brand: "Lancôme", price: 20, category: "mascara", image: "https://m.media-amazon.com/images/I/715veZsKWHL._AC_UF1000,1000_QL80_.jpg", stock: 50, description: "Experience drama with this iconic mascara that delivers extreme volume and definition. The unique brush design coats each lash from root to tip, separating and volumizing for a stunning, fanned-out effect. The黑 mascara formula is enriched with ceramide R to nourish lashes while providing long-lasting wear. Clump-free and smudge-proof for all-day impact.", rating: 4.8, reviewCount: 234 },
  { name: "The Coffee Shop Palette", brand: "Juvia's Place", price: 52, category: "eyeshadow", image: "https://www.juviasplace.com/cdn/shop/products/IMG_6160_1080x.jpg?v=1689050740", stock: 28, description: "Inspired by cozy coffee shop vibes, this warm-toned palette features 9 rich, pigmented shades perfect for creating everyday and editorial looks. The mix of mattes and shimmers works beautifully together for endless combinations. The buttery-soft formulas are highly blendable and long-lasting without fallout. Vegan and cruelty-free with no compromise on color payoff.", rating: 4.9, reviewCount: 178, isTrending: true },
  { name: "Tinted Moisturizer", brand: "NARS", price: 46, category: "foundation", image: "https://m.media-amazon.com/images/I/71s2RWQrufL._SL1500_.jpg", stock: 45, description: "Get naturally beautiful skin with this lightweight tinted moisturizer. The sheer, buildable formula provides a hint of coverage to even out skin tone while letting your natural radiance shine through. Enriched with ingredients like Vitamin E and SPF 20, it protects and nourishes skin while giving you that fresh, no-makeup makeup look. Perfect for those who want light coverage with skincare benefits.", rating: 4.6, reviewCount: 256 },
  { name: "Sleeping Mask Set", brand: "Laneige", price: 28, category: "skincare", image: "https://m.media-amazon.com/images/I/71GH5Doz3HL._SL1500_.jpg", stock: 50, description: "Wake up to hydrated, plump skin with Laneige's famous Sleeping Mask. This leave-on overnight treatment creates a moisture barrier that locks in hydration while you sleep. The lightweight gel texture feels refreshing and absorbs quickly. The water science complex delivers intensive hydration, leaving skin soft, supple, and glowing by morning.", rating: 4.7, reviewCount: 189 },
  { name: "Bath Bomb Set", brand: "Lush", price: 32, category: "skincare", image: "https://www.lush.com/cdn-cgi/image/width=1920,f=auto/https://unicorn.lush.com/media/thumbnails/products/relax_gift_portrait_hero_2024_38fcc11a_thumbnail_4096.jpg", stock: 40, description: "Transform your bath into a spa experience with this collection of handcrafted bath bombs. Each colorful, fragrant bomb fizzes and dissolves to release skin-softening ingredients, essential oils, and beautiful colors. Made with fresh, natural ingredients and essential oils for a truly luxurious bathing experience. Set includes a variety of bestselling scents.", rating: 4.8, reviewCount: 145 },
  { name: "Brush Cleaning Mat", brand: "Sigma", price: 15, category: "other", image: "https://m.media-amazon.com/images/I/81P87NyBiIL.jpg", stock: 80, description: "Keep your makeup brushes clean and extend their lifespan with this innovative cleaning mat. The textured surface features multiple pad sizes and patterns to effectively clean brushes of all sizes. Simply add cleanser and swirl to remove buildup, bacteria, and old product. The suction base keeps the mat firmly in place during use. Cleaning your brushes regularly ensures better makeup application and healthier skin.", rating: 4.5, reviewCount: 234 },
  { name: "Makeup Remover Balm", brand: "Banila Co", price: 24, category: "skincare", image: "https://morgenfreude.com/cdn/shop/files/Sdbf6a2df494c4da2bc2ffb79737614a8N.webp?v=1712647216&width=1445", stock: 55, description: "Dissolve away makeup effortlessly with this cult-favorite cleansing balm. The sherbet-textured formula melts into skin to break down even the most stubborn makeup, sunscreen, and daily grime without stripping or irritating. Simply massage onto dry skin, add water to emulsify, and rinse clean. Leaves skin soft, clean, and perfectly prepped for your skincare routine.", rating: 4.8, reviewCount: 312, colors: [
    { name: "Original", hex: "#eac7d9" },
    { name: "Pore Clarifying", hex: "#cbe6c2" },
    { name: "Revitalizing", hex: "#92cfcd" },
    { name: "Purifying", hex: "#d4d6eb" },
    { name: "Nourishing", hex: "#e2ddaa" }
  ]},
  { name: "Eyelash Curler", brand: "Shu Uemura", price: 22, category: "mascara", image: "https://www.novela.com.sg/asset/ZVkwRjFpRHJzbEhSNEFPRWxCaVZsQjVJT1praDBKR0oySklVSGt0Y1VjWHhadUNsWUhOaWVhWUxPVDNiaFZmdnhXZzRyYjRZSGdUUURZWWFwT24vWjJJZ1RIekZFcTM1R1kxQjNPWGpTZDFGOTJETTNPY0dyREhNaHVVWC9JNGU", stock: 45, description: "Achieve the perfect curl with this professional-grade eyelash curler. The signature curved design fits most eye shapes perfectly, while the smooth rubber pads provide a gentle, even curl without pinching. The steel construction ensures durability and consistent performance. Creates a natural-looking curl that opens up the eyes for a more awake, youthful appearance.", rating: 4.7, reviewCount: 167 },
  { name: "Color Corrector Palette", brand: "NYX", price: 30, category: "makeup", image: "https://cdn.idealo.com/folder/Product/5328/9/5328965/s4_produktbild_max_15/nyx-color-correcting-palette.jpg", stock: 60, description: "Neutralize skin imperfections like a pro with this color-correcting palette. Each shade targets specific concerns: green cancels redness, peach or salmon corrects dark circles, yellow brightens, lavender brightens sallow skin, and more. The blendable, pigmented formulas layer seamlessly under or over foundation for flawless coverage. Perfect for achieving a camera-ready, even complexion.", rating: 4.6, reviewCount: 223, shadeVariants: [
    { name: "Color Correcting Palette", shades: ["#f0c571", "#9accb1", "#ab9cb1", "#dd9b7b", "#d79c7a", "#ae7c4b"] },
    { name: "Deep", shades: ["#e58f54", "#b26b33", "#d58d52", "#703410", "#fbba69", "#c3622b"] },
    { name: "Light", shades: ["#e0a36c", "#e79e69", "#c28954", "#b26f3a", "#f1c16d", "#efa173"] },
    { name: "Medium", shades: ["#e0aa7e", "#e4ae8a", "#dfab7c", "#92664b", "#f2ca96", "#e8a686"] }
  ]},
  { name: "Hair Serum - Argan", brand: "Moroccanoil", price: 26, category: "skincare", image: "https://fr.moroccanoil.com/cdn/shop/products/d1875_digital_brand_mot_ppage_content_resizes_d1752_4_1.jpg?v=1767622870&width=1946", stock: 50, description: "The original argan oil hair treatment that started the buzz. This iconic hair serum infuses hair with antioxidant-rich argan oil to hydrate, smooth, and add brilliant shine. It speeds up drying time, eliminates frizz, and tames flyaways while protecting against heat styling. A little goes a long way - apply to damp or dry hair for silky, healthy-looking locks.", rating: 4.7, reviewCount: 198 },
  { name: "Body Lotion Set - Beija Flor", brand: "Sol de Janeiro", price: 36, category: "skincare", image: "https://chikshop.ma/wp-content/uploads/2024/06/SOL-DE-JANEIRO-Beija-Flor-Jet-Set-Coffret-Soin-Corps-1.webp", stock: 35, description: "Indulge in the irresistible scent of Brazil with this body lotion gift set. Each lotion features the signature Cheirosa '89 fragrance combining pistachio, salted caramel, and vanilla for a delicious, addictive smell. The fast-absorbing formula deeply hydrates while the shimmering effect leaves skin glowing. The set includes multiple sizes perfect for keeping at home or taking on the go.", rating: 4.8, reviewCount: 145 },
  { name: "Mirror - Lighted", brand: "Simplehuman", price: 45, category: "other", image: "https://m.media-amazon.com/images/I/81G2LeSv-9L._AC_UF894,1000_QL80_.jpg", stock: 25, description: "Apply flawless makeup every time with this professional-grade lighted mirror. The 10x magnification lets you see every detail, while the smart dimming feature adjusts to your environment. The true-color, distortion-free mirror provides accurate color representation. The motion-activated sensor turns the light on when you approach and off when you leave. Rechargeable with a USB cable for cordless convenience.", rating: 4.9, reviewCount: 89 },
  { name: "Self Tan Contour Kit", brand: "Bondi Sands", price: 40, category: "skincare", image: "https://static.thcdn.com/productimg/original/14979343-1665172482762556.jpg", stock: 40, description: "Get sculpted, sun-kissed skin without the sun with this innovative self-tanning and contouring kit. The lightweight formulas blend seamlessly for a natural-looking tan that develops in just 4-8 hours. The contour sticks help define and sculpt features for a more chiseled appearance. streak-free and transfer-resistant for a flawless finish that lasts up to a week.", rating: 4.5, reviewCount: 167 },
  { name: "Compact Powder", brand: "Shiseido", price: 32, category: "makeup", image: "https://www.bigw.com.au/medias/sys_master/images/images/h0f/hff/101994346741790.jpg", stock: 50, description: "Set and perfect your makeup with this Japanese-made compact powder. The ultra-fine particles absorb excess oil and blur pores for a smooth, matte finish. The sheer coverage can be built up for light coverage or used over foundation for a polished look. The elegant compact is perfect for touch-ups on the go, leaving skin looking fresh and flawless all day.", rating: 4.6, reviewCount: 189 },
  { name: "Body Scrub - Coffee", brand: "Frank Body", price: 28, category: "skincare", image: "https://i5.walmartimages.com/asr/37a303c7-d491-462b-985f-4962894f6bf4.7e719bc76a6e9b4c7ee9409d7a420829.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF", stock: 55, description: "Wake up your skin with this cult-favorite coffee body scrub. The real coffee grounds gently exfoliate dead skin cells while the caffeine stimulates blood flow for smoother, firmer-looking skin. Enriched with vitamin E and hydrating oils, it nourishes while you scrub. The invigorating coffee scent energizes your senses. Perfect for prepping skin for fake tan or just for that fresh, smooth feeling.", rating: 4.7, reviewCount: 234 }
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    
    await Product.deleteMany({});
    await Product.insertMany(products);
    
    const adminExists = await User.findOne({ email: "admin@makeupshop.com" });
    if (!adminExists) {
      await User.create({
        name: "Admin",
        email: "admin@makeupshop.com",
        password: "admin123",
        isAdmin: true
      });
      console.log("Admin user created: admin@makeupshop.com / admin123");
    }
    
    console.log(`Database seeded with ${products.length} products!`);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedDB();
